sonar.projectKey=eduplain-backend
sonar.projectName=Eduplain Backend
sonar.sourceEncoding=UTF-8
sonar.sources=apps,config
sonar.tests=apps/health/tests,apps/users/tests
sonar.test.inclusions=**/tests/test_*.py
sonar.exclusions=**/migrations/**,**/__pycache__/**
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
